#!/usr/bin/env bash
#
# Git pre-commit hook
#

# Tests
echo "😇  [TEST] Running 'make test'"
make test
result=$?
if [ $result -ne 0 ]; then
    echo ''
    echo '🌋  [FAIL] Unit tests have failed'
    echo ''
    exit 1
fi


# We are finished with all of this now
echo ''